# Generated by Django 2.2.1 on 2019-05-15 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='helpful',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Helpful for this users'),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Helpful for this users'),
        ),
    ]
