# Generated by Django 2.2.3 on 2019-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20190605_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_hiring',
            field=models.BooleanField(default=False, verbose_name='Is hiring'),
        ),
    ]
