# Generated by Django 2.2.4 on 2019-08-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_subscription_is_trial'),
        ('reviews', '0008_auto_20190808_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='finished_at',
            field=models.DateField(null=True, verbose_name='Finished working at'),
        ),
        migrations.AddField(
            model_name='review',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.Position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='review',
            name='started_at',
            field=models.DateField(null=True, verbose_name='Started working at'),
        ),
    ]
