# Generated by Django 2.2.1 on 2019-05-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_vacancy_receptive'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_vacancies',
            field=models.ManyToManyField(related_name='users', to='companies.Vacancy', verbose_name='Favorite vacancies'),
        ),
    ]
