# Generated by Django 2.2.1 on 2019-05-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_vacancies',
        ),
    ]
