# Generated by Django 2.2.3 on 2019-07-02 11:31

from django.db import migrations, models
import jobadvisor.common.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_favorite_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to=jobadvisor.common.helpers.upload_to),
        ),
    ]
