repos:
  # Pre commit
  - repo: https://gitlab.com/PyCQA/flake8
    rev: master
    hooks:
      - id: flake8
        additional_dependencies:
          - 'flake8-docstrings'
          - 'pydocstyle==3.0.0'
          - 'flake8-quotes'
          - 'flake8-print'
        args: ['jobadvisor']
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
      - id: isort
        args: ['jobadvisor']
  - repo: https://github.com/PyCQA/bandit
    rev: master
    hooks:
      - id: bandit
        args: ['-s', 'B101', '-r', 'jobadvisor']
