# Generated by Django 2.2.4 on 2019-09-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Weight'),
        ),
    ]
