# Generated by Django 2.2.2 on 2019-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_advantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
