# Generated by Django 2.2.3 on 2019-07-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190605_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'Trainee'), (1, 'Employee'), (2, 'Employer')], default=1, verbose_name='User level'),
        ),
    ]
