# Generated by Django 2.2.3 on 2019-07-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_advantage_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='role',
            new_name='level',
        ),
    ]
