# Generated by Django 2.2.3 on 2019-07-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190719_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='level',
            field=models.IntegerField(choices=[(0, 'Trainee'), (1, 'Employee'), (2, 'Employer')], help_text='Select level', verbose_name='Level'),
        ),
    ]
