# Generated by Django 2.2.3 on 2019-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190719_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Page title')),
                ('slug', models.SlugField(unique=True, verbose_name='Page slug')),
                ('text', models.TextField(verbose_name='Page text')),
            ],
        ),
    ]
