environment: "production"
siteUrl: https://prod.jobadvisor.staging.by
debug: "false"
allowedHosts:
  - "*"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
  hosts:
    - host: api-prod.jobadvisor.staging.by
      paths: [/]
  tls:
    - secretName: prod-staging-api-jobadvisor-tls
      hosts:
        - api-prod.jobadvisor.staging.by