# Generated by Django 2.2.4 on 2019-08-20 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', 'Warning'), ('info', 'Info'), ('success', 'Success'), ('alarm', 'Alarm')], max_length=12, verbose_name='Level')),
                ('text', models.TextField(verbose_name='Text')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Is delivered')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
