# Generated by Django 2.2 on 2019-05-02 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='receptive',
            field=models.ManyToManyField(related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Receptive to the offer'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.Industry', verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.ManyToManyField(related_name='workings', to=settings.AUTH_USER_MODEL, verbose_name='Workers'),
        ),
    ]
