# Generated by Django 2.2.1 on 2019-05-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20190503_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='receptive',
        ),
    ]
