# Generated by Django 2.2.1 on 2019-05-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_vacancy_receptive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-pk'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['-pk'], 'verbose_name': 'Industry', 'verbose_name_plural': 'Industry'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-pk'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-pk'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-pk'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
