# Generated by Django 2.2.1 on 2019-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20190511_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Participates in the top'),
        ),
    ]
