# Generated by Django 2.2.1 on 2019-05-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20190511_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-is_top', '-pk'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
