# Generated by Django 2.2.1 on 2019-05-13 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20190513_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(related_name='following', through='companies.Follow', to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
    ]
