# Generated by Django 2.2.1 on 2019-05-17 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0013_auto_20190513_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='responded_users',
            field=models.ManyToManyField(related_name='responded_vacancies', to=settings.AUTH_USER_MODEL),
        ),
    ]
