# Generated by Django 2.2.4 on 2019-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20190722_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Is trial'),
        ),
    ]
