# Generated by Django 2.2.4 on 2019-08-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_subscription_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='This is the best'),
        ),
    ]
